// Code generated by goctl. DO NOT EDIT.
// Source: shippingAddrs.proto

package server

import (
	"context"

	"github.com/dinzhen12306/shippingAddr/internal/logic"
	"github.com/dinzhen12306/shippingAddr/internal/svc"
	"github.com/dinzhen12306/shippingAddr/shippingAddrs"
)

type ShippingAddrServer struct {
	svcCtx *svc.ServiceContext
	shippingAddrs.UnimplementedShippingAddrServer
}

func NewShippingAddrServer(svcCtx *svc.ServiceContext) *ShippingAddrServer {
	return &ShippingAddrServer{
		svcCtx: svcCtx,
	}
}

func (s *ShippingAddrServer) GetShippingAddrList(ctx context.Context, in *shippingAddrs.GetShippingAddrListReq) (*shippingAddrs.GetShippingAddrListResp, error) {
	l := logic.NewGetShippingAddrListLogic(ctx, s.svcCtx)
	return l.GetShippingAddrList(in)
}

func (s *ShippingAddrServer) GetShippingAddr(ctx context.Context, in *shippingAddrs.GetShippingAddrReq) (*shippingAddrs.GetShippingAddrResp, error) {
	l := logic.NewGetShippingAddrLogic(ctx, s.svcCtx)
	return l.GetShippingAddr(in)
}

func (s *ShippingAddrServer) CreateShippingAddr(ctx context.Context, in *shippingAddrs.CreateShippingAddrReq) (*shippingAddrs.CreateShippingAddrResp, error) {
	l := logic.NewCreateShippingAddrLogic(ctx, s.svcCtx)
	return l.CreateShippingAddr(in)
}

func (s *ShippingAddrServer) UpdateShippingAddr(ctx context.Context, in *shippingAddrs.UpdateShippingAddrReq) (*shippingAddrs.UpdateShippingAddrResp, error) {
	l := logic.NewUpdateShippingAddrLogic(ctx, s.svcCtx)
	return l.UpdateShippingAddr(in)
}

func (s *ShippingAddrServer) DeleteShippingAddr(ctx context.Context, in *shippingAddrs.DeleteShippingAddrReq) (*shippingAddrs.DeleteShippingAddrResp, error) {
	l := logic.NewDeleteShippingAddrLogic(ctx, s.svcCtx)
	return l.DeleteShippingAddr(in)
}
