// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.19.4
// source: shippingAddrs.proto

package shippingAddrs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShippingAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID              int64  `protobuf:"varint,10,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID          int64  `protobuf:"varint,20,opt,name=UserID,proto3" json:"UserID,omitempty"`
	RecipientName   string `protobuf:"bytes,30,opt,name=RecipientName,proto3" json:"RecipientName,omitempty"`
	PhoneNumber     string `protobuf:"bytes,40,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Location        string `protobuf:"bytes,50,opt,name=Location,proto3" json:"Location,omitempty"`
	DetailedAddress string `protobuf:"bytes,60,opt,name=DetailedAddress,proto3" json:"DetailedAddress,omitempty"`
	Tabs            string `protobuf:"bytes,70,opt,name=Tabs,proto3" json:"Tabs,omitempty"`
	IsDefault       int64  `protobuf:"varint,80,opt,name=IsDefault,proto3" json:"IsDefault,omitempty"`
}

func (x *ShippingAddress) Reset() {
	*x = ShippingAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShippingAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingAddress) ProtoMessage() {}

func (x *ShippingAddress) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingAddress.ProtoReflect.Descriptor instead.
func (*ShippingAddress) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingAddress) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ShippingAddress) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ShippingAddress) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *ShippingAddress) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ShippingAddress) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ShippingAddress) GetDetailedAddress() string {
	if x != nil {
		return x.DetailedAddress
	}
	return ""
}

func (x *ShippingAddress) GetTabs() string {
	if x != nil {
		return x.Tabs
	}
	return ""
}

func (x *ShippingAddress) GetIsDefault() int64 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

type GetShippingAddrListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Where map[string]string `protobuf:"bytes,10,rep,name=Where,proto3" json:"Where,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetShippingAddrListReq) Reset() {
	*x = GetShippingAddrListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShippingAddrListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShippingAddrListReq) ProtoMessage() {}

func (x *GetShippingAddrListReq) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShippingAddrListReq.ProtoReflect.Descriptor instead.
func (*GetShippingAddrListReq) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{1}
}

func (x *GetShippingAddrListReq) GetWhere() map[string]string {
	if x != nil {
		return x.Where
	}
	return nil
}

type GetShippingAddrListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ShippingAddress `protobuf:"bytes,10,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetShippingAddrListResp) Reset() {
	*x = GetShippingAddrListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShippingAddrListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShippingAddrListResp) ProtoMessage() {}

func (x *GetShippingAddrListResp) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShippingAddrListResp.ProtoReflect.Descriptor instead.
func (*GetShippingAddrListResp) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{2}
}

func (x *GetShippingAddrListResp) GetData() []*ShippingAddress {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetShippingAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Where map[string]string `protobuf:"bytes,10,rep,name=Where,proto3" json:"Where,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetShippingAddrReq) Reset() {
	*x = GetShippingAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShippingAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShippingAddrReq) ProtoMessage() {}

func (x *GetShippingAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShippingAddrReq.ProtoReflect.Descriptor instead.
func (*GetShippingAddrReq) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{3}
}

func (x *GetShippingAddrReq) GetWhere() map[string]string {
	if x != nil {
		return x.Where
	}
	return nil
}

type GetShippingAddrResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ShippingAddress `protobuf:"bytes,10,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetShippingAddrResp) Reset() {
	*x = GetShippingAddrResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShippingAddrResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShippingAddrResp) ProtoMessage() {}

func (x *GetShippingAddrResp) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShippingAddrResp.ProtoReflect.Descriptor instead.
func (*GetShippingAddrResp) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{4}
}

func (x *GetShippingAddrResp) GetData() *ShippingAddress {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateShippingAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ShippingAddress `protobuf:"bytes,10,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *CreateShippingAddrReq) Reset() {
	*x = CreateShippingAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShippingAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShippingAddrReq) ProtoMessage() {}

func (x *CreateShippingAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShippingAddrReq.ProtoReflect.Descriptor instead.
func (*CreateShippingAddrReq) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShippingAddrReq) GetData() *ShippingAddress {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateShippingAddrResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,10,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *CreateShippingAddrResp) Reset() {
	*x = CreateShippingAddrResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShippingAddrResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShippingAddrResp) ProtoMessage() {}

func (x *CreateShippingAddrResp) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShippingAddrResp.ProtoReflect.Descriptor instead.
func (*CreateShippingAddrResp) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{6}
}

func (x *CreateShippingAddrResp) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type UpdateShippingAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ShippingAddress `protobuf:"bytes,10,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *UpdateShippingAddrReq) Reset() {
	*x = UpdateShippingAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateShippingAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShippingAddrReq) ProtoMessage() {}

func (x *UpdateShippingAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShippingAddrReq.ProtoReflect.Descriptor instead.
func (*UpdateShippingAddrReq) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateShippingAddrReq) GetData() *ShippingAddress {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateShippingAddrResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,10,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *UpdateShippingAddrResp) Reset() {
	*x = UpdateShippingAddrResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateShippingAddrResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShippingAddrResp) ProtoMessage() {}

func (x *UpdateShippingAddrResp) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShippingAddrResp.ProtoReflect.Descriptor instead.
func (*UpdateShippingAddrResp) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateShippingAddrResp) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteShippingAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,10,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteShippingAddrReq) Reset() {
	*x = DeleteShippingAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShippingAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShippingAddrReq) ProtoMessage() {}

func (x *DeleteShippingAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShippingAddrReq.ProtoReflect.Descriptor instead.
func (*DeleteShippingAddrReq) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteShippingAddrReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteShippingAddrResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteShippingAddrResp) Reset() {
	*x = DeleteShippingAddrResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shippingAddr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShippingAddrResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShippingAddrResp) ProtoMessage() {}

func (x *DeleteShippingAddrResp) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShippingAddrResp.ProtoReflect.Descriptor instead.
func (*DeleteShippingAddrResp) Descriptor() ([]byte, []int) {
	return file_shippingAddr_proto_rawDescGZIP(), []int{10}
}

var File_shippingAddr_proto protoreflect.FileDescriptor

var file_shippingAddr_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x22, 0xf9, 0x01, 0x0a, 0x0f, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x24,
	0x0a, 0x0d, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x28, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x32, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x61, 0x62, 0x73, 0x18, 0x46, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x62, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x50, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x49, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x99,
	0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x45, 0x0a, 0x05, 0x57, 0x68, 0x65,
	0x72, 0x65, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x57,
	0x68, 0x65, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x57, 0x68, 0x65, 0x72, 0x65,
	0x1a, 0x38, 0x0a, 0x0a, 0x57, 0x68, 0x65, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4c, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x91, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x41, 0x0a, 0x05, 0x57, 0x68, 0x65, 0x72, 0x65, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71,
	0x2e, 0x57, 0x68, 0x65, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x57, 0x68, 0x65,
	0x72, 0x65, 0x1a, 0x38, 0x0a, 0x0a, 0x57, 0x68, 0x65, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x48, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72,
	0x2e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x31, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x53, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x4a, 0x0a, 0x15,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x28, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x44, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x18, 0x0a, 0x16, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x32, 0xed, 0x03, 0x0a, 0x0c, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x12, 0x62, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e,
	0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x56, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20, 0x2e,
	0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x21, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x5f, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x12, 0x23, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68,
	0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e,
	0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x5f, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x12, 0x23, 0x2e, 0x73, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x24,
	0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x5f, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68,
	0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x12, 0x23, 0x2e, 0x73, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x24, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x73, 0x68, 0x69, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shippingAddr_proto_rawDescOnce sync.Once
	file_shippingAddr_proto_rawDescData = file_shippingAddr_proto_rawDesc
)

func file_shippingAddr_proto_rawDescGZIP() []byte {
	file_shippingAddr_proto_rawDescOnce.Do(func() {
		file_shippingAddr_proto_rawDescData = protoimpl.X.CompressGZIP(file_shippingAddr_proto_rawDescData)
	})
	return file_shippingAddr_proto_rawDescData
}

var file_shippingAddr_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_shippingAddr_proto_goTypes = []interface{}{
	(*ShippingAddress)(nil),         // 0: shippingAddrs.ShippingAddress
	(*GetShippingAddrListReq)(nil),  // 1: shippingAddrs.GetShippingAddrListReq
	(*GetShippingAddrListResp)(nil), // 2: shippingAddrs.GetShippingAddrListResp
	(*GetShippingAddrReq)(nil),      // 3: shippingAddrs.GetShippingAddrReq
	(*GetShippingAddrResp)(nil),     // 4: shippingAddrs.GetShippingAddrResp
	(*CreateShippingAddrReq)(nil),   // 5: shippingAddrs.CreateShippingAddrReq
	(*CreateShippingAddrResp)(nil),  // 6: shippingAddrs.CreateShippingAddrResp
	(*UpdateShippingAddrReq)(nil),   // 7: shippingAddrs.UpdateShippingAddrReq
	(*UpdateShippingAddrResp)(nil),  // 8: shippingAddrs.UpdateShippingAddrResp
	(*DeleteShippingAddrReq)(nil),   // 9: shippingAddrs.DeleteShippingAddrReq
	(*DeleteShippingAddrResp)(nil),  // 10: shippingAddrs.DeleteShippingAddrResp
	nil,                             // 11: shippingAddrs.GetShippingAddrListReq.WhereEntry
	nil,                             // 12: shippingAddrs.GetShippingAddrReq.WhereEntry
}
var file_shippingAddr_proto_depIdxs = []int32{
	11, // 0: shippingAddrs.GetShippingAddrListReq.Where:type_name -> shippingAddrs.GetShippingAddrListReq.WhereEntry
	0,  // 1: shippingAddrs.GetShippingAddrListResp.Data:type_name -> shippingAddrs.ShippingAddress
	12, // 2: shippingAddrs.GetShippingAddrReq.Where:type_name -> shippingAddrs.GetShippingAddrReq.WhereEntry
	0,  // 3: shippingAddrs.GetShippingAddrResp.Data:type_name -> shippingAddrs.ShippingAddress
	0,  // 4: shippingAddrs.CreateShippingAddrReq.Data:type_name -> shippingAddrs.ShippingAddress
	0,  // 5: shippingAddrs.UpdateShippingAddrReq.Data:type_name -> shippingAddrs.ShippingAddress
	1,  // 6: shippingAddrs.ShippingAddr.GetShippingAddrList:input_type -> shippingAddrs.GetShippingAddrListReq
	3,  // 7: shippingAddrs.ShippingAddr.GetShippingAddr:input_type -> shippingAddrs.GetShippingAddrReq
	5,  // 8: shippingAddrs.ShippingAddr.CreateShippingAddr:input_type -> shippingAddrs.CreateShippingAddrReq
	7,  // 9: shippingAddrs.ShippingAddr.UpdateShippingAddr:input_type -> shippingAddrs.UpdateShippingAddrReq
	9,  // 10: shippingAddrs.ShippingAddr.DeleteShippingAddr:input_type -> shippingAddrs.DeleteShippingAddrReq
	2,  // 11: shippingAddrs.ShippingAddr.GetShippingAddrList:output_type -> shippingAddrs.GetShippingAddrListResp
	4,  // 12: shippingAddrs.ShippingAddr.GetShippingAddr:output_type -> shippingAddrs.GetShippingAddrResp
	6,  // 13: shippingAddrs.ShippingAddr.CreateShippingAddr:output_type -> shippingAddrs.CreateShippingAddrResp
	8,  // 14: shippingAddrs.ShippingAddr.UpdateShippingAddr:output_type -> shippingAddrs.UpdateShippingAddrResp
	10, // 15: shippingAddrs.ShippingAddr.DeleteShippingAddr:output_type -> shippingAddrs.DeleteShippingAddrResp
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_shippingAddr_proto_init() }
func file_shippingAddr_proto_init() {
	if File_shippingAddr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shippingAddr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShippingAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShippingAddrListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShippingAddrListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShippingAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShippingAddrResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShippingAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShippingAddrResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateShippingAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateShippingAddrResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShippingAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shippingAddr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShippingAddrResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shippingAddr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shippingAddr_proto_goTypes,
		DependencyIndexes: file_shippingAddr_proto_depIdxs,
		MessageInfos:      file_shippingAddr_proto_msgTypes,
	}.Build()
	File_shippingAddr_proto = out.File
	file_shippingAddr_proto_rawDesc = nil
	file_shippingAddr_proto_goTypes = nil
	file_shippingAddr_proto_depIdxs = nil
}
